### ISSUE TITLE
Footer sivulle 

### ISSUE THREAD

**Issue by NuoriPadawan** [Lekarki/reviewsite#7]
Lue otsikko

**Comment by jonlaidev** [comment]
<footer>
        <div class="footer">
            <div class="row">
        
        <ul>
            <li><a href="https://blank.page/">Yhteystiedot</a></li>
            <li><a href="https://blank.page/">Yksityisyys</a></li>
            <li><a href="https://blank.page/">Käyttöehdot</a></li>
        </ul>
            </div>

        <div class="footer_logo">
            <a href="index.html">
            <img src="../img/pelaajanexus_logo_pieni.jpg" alt="logo">
            </a>
        </div>    
        
        <div class="row">
        Copyright © 2024 - All rights reserved | Suunnittelu: Joni, Leevi & Patrik
        </div>
        </div>
    </footer>

**Comment by jonlaidev** [comment]
Tehty

**Comment by NuoriPadawan** [comment]
komiaa
